services:
  
  sql:
    image: postgres
    restart: always
    
    environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: Password@123
        PGDATA: /var/lib/postgresql/data/pgdata
        
    volumes:
      - /Users/hoseinnahari/Documents/ReactivityDatabase/data:/var/lib/postgresql/data
        
    ports:
      - "5432:5432"